package org.paypal.hackathon.project.persistence.bean;

import static javax.persistence.GenerationType.IDENTITY;

// Generated Jul 20, 2014 7:01:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.math.NumberUtils;

/**
 * VendorInformation generated by hbm2java
 */
@Entity
@Table(name = "vendor_information", catalog = "gazeteer")
public class VendorInformation implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8868287505148942837L;
	private Long vendorInformationId;
	private String vendorName;
	private String vendorDescription;
	private String vendorAdressLine1;
	private String vendorAdressLine2;
	private String vendorAdressLine3;
	private String vendorCity;
	private String vendorState;
	private String vendorMobileNumber;
	private String vendorLandlineNumber;
	private String vendorFacebookAddress;
	private String vendorTwitterAddress;
	private String vendorGoogleMapAddress;
	private String vendorWebSiteAddress;
	private String vendorBusinessTags;
	private String vendorEmailAddress;
	private int vendorCategoryId = -1;
	private int vendorPriorityId = -1;
	private int vendorTypeId = -1;
	private boolean billingPerCall;
	private boolean recieveSMS;
	private boolean disabled;

	public VendorInformation() {
		vendorName = StringUtils.EMPTY;
		vendorDescription = StringUtils.EMPTY;
		vendorAdressLine1 = StringUtils.EMPTY;
		vendorCity = StringUtils.EMPTY;
		vendorState = StringUtils.EMPTY;
		vendorMobileNumber = StringUtils.EMPTY;
		vendorLandlineNumber = StringUtils.EMPTY;
		vendorCategoryId = NumberUtils.INTEGER_ZERO;
		vendorPriorityId = NumberUtils.INTEGER_ZERO;
		vendorTypeId = NumberUtils.INTEGER_ZERO;
		billingPerCall = Boolean.FALSE;
		recieveSMS = Boolean.FALSE;
	}

	public VendorInformation(Long vendorInformationId, String vendorName, String vendorDescription,
			String vendorAdressLine1, String vendorAdressLine2, String vendorAdressLine3, String vendorCity,
			String vendorState, String vendorMobileNumber, String vendorLandlineNumber, String vendorFacebookAddress,
			String vendorTwitterAddress, String vendorGoogleMapAddress, String vendorWebSiteAddress,
			int vendorCategoryId, int vendorPriorityId, int vendorTypeId, boolean billingPerCall, boolean recieveSMS,
			boolean disabled) {
		super();
		this.vendorInformationId = vendorInformationId;
		this.vendorName = vendorName;
		this.vendorDescription = vendorDescription;
		this.vendorAdressLine1 = vendorAdressLine1;
		this.vendorAdressLine2 = vendorAdressLine2;
		this.vendorAdressLine3 = vendorAdressLine3;
		this.vendorCity = vendorCity;
		this.vendorState = vendorState;
		this.vendorMobileNumber = vendorMobileNumber;
		this.vendorLandlineNumber = vendorLandlineNumber;
		this.vendorFacebookAddress = vendorFacebookAddress;
		this.vendorTwitterAddress = vendorTwitterAddress;
		this.vendorGoogleMapAddress = vendorGoogleMapAddress;
		this.vendorWebSiteAddress = vendorWebSiteAddress;
		this.vendorCategoryId = vendorCategoryId;
		this.vendorPriorityId = vendorPriorityId;
		this.vendorTypeId = vendorTypeId;
		this.billingPerCall = billingPerCall;
		this.recieveSMS = recieveSMS;
		this.disabled = disabled;
	}

	public VendorInformation(String vendorName, String vendorDescription, String vendorAdressLine1, String vendorCity,
			String vendorState, String vendorMobileNumber, String vendorLandlineNumber, int vendorCategoryId,
			int vendorPriorityId, int vendorTypeId, boolean billingPerCall) {
		this.vendorName = vendorName;
		this.vendorDescription = vendorDescription;
		this.vendorAdressLine1 = vendorAdressLine1;
		this.vendorCity = vendorCity;
		this.vendorState = vendorState;
		this.vendorMobileNumber = vendorMobileNumber;
		this.vendorLandlineNumber = vendorLandlineNumber;
		this.vendorCategoryId = vendorCategoryId;
		this.vendorPriorityId = vendorPriorityId;
		this.vendorTypeId = vendorTypeId;
		this.billingPerCall = billingPerCall;
	}

	@Column(name = "vendor_adress_line1", nullable = false, length = 100)
	public String getVendorAdressLine1() {
		return vendorAdressLine1;
	}

	@Column(name = "vendor_adress_line2", length = 100)
	public String getVendorAdressLine2() {
		return vendorAdressLine2;
	}

	@Column(name = "vendor_adress_line3", length = 100)
	public String getVendorAdressLine3() {
		return vendorAdressLine3;
	}

	@Column(name = "business_tags", nullable = false)
	public String getVendorBusinessTags() {
		return vendorBusinessTags;
	}

	@Column(name = "vendor_category_id", nullable = false)
	public int getVendorCategoryId() {
		return vendorCategoryId;
	}

	@Column(name = "vendor_city", nullable = false, length = 100)
	public String getVendorCity() {
		return vendorCity;
	}

	@Column(name = "vendor_description", nullable = false, length = 200)
	public String getVendorDescription() {
		return vendorDescription;
	}

	@Column(name = "email_address", nullable = true)
	public String getVendorEmailAddress() {
		return vendorEmailAddress;
	}

	@Column(name = "vendor_facebook_address", length = 100)
	public String getVendorFacebookAddress() {
		return vendorFacebookAddress;
	}

	@Column(name = "vendor_google_map_address", length = 300)
	public String getVendorGoogleMapAddress() {
		return vendorGoogleMapAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "vendor_information_id", unique = true, nullable = false)
	public Long getVendorInformationId() {
		return vendorInformationId;
	}

	@Column(name = "vendor_landline_number", nullable = false, length = 20)
	public String getVendorLandlineNumber() {
		return vendorLandlineNumber;
	}

	@Column(name = "vendor_mobile_number", nullable = false, length = 20)
	public String getVendorMobileNumber() {
		return vendorMobileNumber;
	}

	@Column(name = "vendor_name", nullable = false, length = 100)
	public String getVendorName() {
		return vendorName;
	}

	@Column(name = "vendor_priority_id", nullable = false)
	public int getVendorPriorityId() {
		return vendorPriorityId;
	}

	@Column(name = "vendor_state", nullable = false, length = 100)
	public String getVendorState() {
		return vendorState;
	}

	@Column(name = "vendor_twitter_address", length = 100)
	public String getVendorTwitterAddress() {
		return vendorTwitterAddress;
	}

	@Column(name = "vendor_type_id", nullable = false)
	public int getVendorTypeId() {
		return vendorTypeId;
	}

	@Column(name = "vendor_web_site_address", length = 100)
	public String getVendorWebSiteAddress() {
		return vendorWebSiteAddress;
	}

	@Column(name = "billing_per_call", nullable = false)
	public boolean isBillingPerCall() {
		return billingPerCall;
	}

	@Column(name = "disabled", nullable = false)
	public boolean isDisabled() {
		return disabled;
	}

	@Column(name = "recieve_sms", nullable = false)
	public boolean isRecieveSMS() {
		return recieveSMS;
	}

	public void setBillingPerCall(boolean billingPerCall) {
		this.billingPerCall = billingPerCall;
	}

	public void setDisabled(boolean disabled) {
		this.disabled = disabled;
	}

	public void setRecieveSMS(boolean recieveSMS) {
		this.recieveSMS = recieveSMS;
	}

	public void setVendorAdressLine1(String vendorAdressLine1) {
		this.vendorAdressLine1 = vendorAdressLine1;
	}

	public void setVendorAdressLine2(String vendorAdressLine2) {
		this.vendorAdressLine2 = vendorAdressLine2;
	}

	public void setVendorAdressLine3(String vendorAdressLine3) {
		this.vendorAdressLine3 = vendorAdressLine3;
	}

	public void setVendorBusinessTags(String vendorBusinessTags) {
		this.vendorBusinessTags = vendorBusinessTags;
	}

	public void setVendorCategoryId(int vendorCategoryId) {
		this.vendorCategoryId = vendorCategoryId;
	}

	public void setVendorCity(String vendorCity) {
		this.vendorCity = vendorCity;
	}

	public void setVendorDescription(String vendorDescription) {
		this.vendorDescription = vendorDescription;
	}

	public void setVendorEmailAddress(String vendorEmailAddress) {
		this.vendorEmailAddress = vendorEmailAddress;
	}

	public void setVendorFacebookAddress(String vendorFacebookAddress) {
		this.vendorFacebookAddress = vendorFacebookAddress;
	}

	public void setVendorGoogleMapAddress(String vendorGoogleMapAddress) {
		this.vendorGoogleMapAddress = vendorGoogleMapAddress;
	}

	public void setVendorInformationId(Long vendorInformationId) {
		this.vendorInformationId = vendorInformationId;
	}

	public void setVendorLandlineNumber(String vendorLandlineNumber) {
		this.vendorLandlineNumber = vendorLandlineNumber;
	}

	public void setVendorMobileNumber(String vendorMobileNumber) {
		this.vendorMobileNumber = vendorMobileNumber;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}

	public void setVendorPriorityId(int vendorPriorityId) {
		this.vendorPriorityId = vendorPriorityId;
	}

	public void setVendorState(String vendorState) {
		this.vendorState = vendorState;
	}

	public void setVendorTwitterAddress(String vendorTwitterAddress) {
		this.vendorTwitterAddress = vendorTwitterAddress;
	}

	public void setVendorTypeId(int vendorTypeId) {
		this.vendorTypeId = vendorTypeId;
	}

	public void setVendorWebSiteAddress(String vendorWebSiteAddress) {
		this.vendorWebSiteAddress = vendorWebSiteAddress;
	}

	@Override
	public String toString() {
		return "VendorInformation [vendorInformationId=" + vendorInformationId + ", vendorName=" + vendorName
				+ ", vendorDescription=" + vendorDescription + ", vendorAdressLine1=" + vendorAdressLine1
				+ ", vendorAdressLine2=" + vendorAdressLine2 + ", vendorAdressLine3=" + vendorAdressLine3
				+ ", vendorCity=" + vendorCity + ", vendorState=" + vendorState + ", vendorMobileNumber="
				+ vendorMobileNumber + ", vendorLandlineNumber=" + vendorLandlineNumber + ", vendorFacebookAddress="
				+ vendorFacebookAddress + ", vendorTwitterAddress=" + vendorTwitterAddress + ", vendorGoogleMapAddress="
				+ vendorGoogleMapAddress + ", vendorWebSiteAddress=" + vendorWebSiteAddress + ", vendorCategoryId="
				+ vendorCategoryId + ", vendorPriorityId=" + vendorPriorityId + ", vendorTypeId=" + vendorTypeId
				+ ", billingPerCall=" + billingPerCall + ", recieveSMS=" + recieveSMS + ", disabled=" + disabled + "]";
	}
}
